# Hyperparameters
BATCH_SIZE = 30
EPOCHS = 500
GAMMA = 0.99
LEARNING_RATE = 3e-4
CLIP_RATIO = 0.2
ENTROPY_COEF = 0.01
QUANTIZATION_THRESHOLD = 0.5  # Action threshold

# Reward Weights
W_COMPRESSION = 0.1
W_ACCURACY = 10.0
W_CLUSTERING = 0.2
TARGET_MSE_THRESHOLD = 0.01

# Debug
ENABLE_DEBUG = True